---

workspace:
  base: /go
  path: src/github.com/packethost/hegel


pipeline:
  lint:
    group: ci
    image: golang:1.10-alpine
    commands:
      - apk add --update --upgrade --no-cache git
      - go get -v -u github.com/alecthomas/gometalinter
      - gometalinter --install
      - gometalinter --errors --vendor --vendored-linters ./...
      - gofmt -d *.go | (! grep '.')

  test:
    group: ci
    image: golang:1.10-alpine
    commands:
      - go test -v ./...

  build:
    group: ci
    image: golang:1.10-alpine
    commands:
      - CGO_ENABLED=0 go build

  publish:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/packet/hegel
    tags:
      - ${DRONE_BRANCH/\//-}
      - ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
    when:
      event: [push]
    secrets: [docker_username, docker_password]

  publish_tag:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/packet/hegel
    tags: ${DRONE_TAG}
    when:
      event: [tag]
    secrets: [docker_username, docker_password]
