// Code generated by MockGen. DO NOT EDIT.
// Source: internal/backend/kubernetes/backend.go

// Package kubernetes is a generated GoMock package.
package kubernetes

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockListerClient is a mock of ListerClient interface.
type MockListerClient struct {
	ctrl     *gomock.Controller
	recorder *MockListerClientMockRecorder
}

// MockListerClientMockRecorder is the mock recorder for MockListerClient.
type MockListerClientMockRecorder struct {
	mock *MockListerClient
}

// NewMockListerClient creates a new mock instance.
func NewMockListerClient(ctrl *gomock.Controller) *MockListerClient {
	mock := &MockListerClient{ctrl: ctrl}
	mock.recorder = &MockListerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListerClient) EXPECT() *MockListerClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockListerClient) List(ctx context.Context, list client.ObjectList, opts ...client.ListOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, list}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockListerClientMockRecorder) List(ctx, list interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, list}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockListerClient)(nil).List), varargs...)
}
